development:
  adapter: postgresql
  encoding: unicode
  database: rails_blog__postgres_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: rails_blog__postgres_test
  pool: 5
  username: postgres
  password: password
